# Generated by Django 2.0.1 on 2020-08-19 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Cooker',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CookerDetail',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('telephone', models.BigIntegerField()),
                ('addr', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('designDate', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Canteen')),
                ('cookers', models.ManyToManyField(to='app01.Cooker')),
            ],
        ),
        migrations.CreateModel(
            name='SaleFood',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('snumber', models.IntegerField()),
                ('foodsale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Food')),
            ],
        ),
        migrations.AddField(
            model_name='cooker',
            name='cookerDetail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.CookerDetail'),
        ),
    ]
