# Generated by Django 2.0.1 on 2020-08-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Book1',
        ),
    ]
